a_million=list(range(1, 1_000_001))
min_value=min(a_million)
max_value=max(a_million)
total=sum(a_million)
average = total / len(a_million)
print(f"min_value: {min_value}")
print(f"max_value: {max_value}")
print(f"Total: {total}")
print(f"Average: {average}")